### PR TITLE
Update join-google-meet.py

### PR DESCRIPTION
**Pull request by harshalg888**
Organizational Domain ID it is!

### CODE REVIEW

**Comment by Patrick780** [comment]
Let's make this script more generic. Instead of having dtu.ac.in or gmail.com, let user have any email address he wants.

**Comment by harshalg888** [comment]
Yeah, good! It will be more flexible. In that case we have to add an "if - else" function so that for users signing in with emails IDs other than DTU domain IDs, our bot will click on "ask to join" button & pause/sleep/wait until a teacher accepts its request.

**Comment by Patrick780** [comment]
The funny thing is, css selector of "Ask to join" and "Join meeting" is
same.. so we don't need to add conditions for them explicitly. It'll work
in both scenarios.

**Comment by harshalg888** [comment]
Ohh....Okay then!

**Pull request closed without merging**
